### ISSUE TITLE
Error generating bindings

### ISSUE THREAD

**Issue by bararchy** [ysbaddaden/clang.cr#2]
```bash
./c2cr -I/usr/include/tensorflow/c/c_api.h --remove-enum-prefix > /tmp/test.cr
Nil assertion failed (Exception)
0x557950334ef0: not_nil! at /usr/lib/crystal/class.cr 65:0
0x5579502f573a: __crystal_main at /home/unshadow/Desktop/git-projects/clang.cr/samples/c2cr.cr 0:3
0x557950305069: main at /usr/lib/crystal/main.cr 12:15
0x7fc688c6ef6a: __libc_start_main at ??
0x5579502f48ea: _start at ??
0x0: ??? at ??
```

Attached c header file to tests
[tensor.zip](https://github.com/ysbaddaden/clang.cr/files/1329656/tensor.zip)

**Comment by ysbaddaden** [comment]
You're missing a header to convert. I improved the error message so it now says:

```sh
$ c2cr -I/usr/include/tensorflow/c/c_api.h --remove-enum-prefix
fatal : no header to create bindings for.
```

What you want is:
```sh
$ c2cr -I/usr/include tensorflow/c/c_api.h --remove-enum-prefix
```

Thought `/usr/include` should have been detected already and thus not necessary. Specifying a header file *is* required, otherwise `c2cr` would be incapable to know whether the AST it's receiving from libclang belongs to the header to convert and thus should generate the bindings, or not.

**Comment by bararchy** [comment]
I see , so it was my bad , its 2 parameters , not 1.

Thanks @ysbaddaden

**Comment by ysbaddaden** [comment]
Well, it's just one parameter: `c2cr [flags] <header.h>` as long as the header can be found in standard locations (detected by running `cc -E - -v`).
