### ISSUE TITLE
Remove crystal_lib?

### ISSUE THREAD

**Issue by asterite** [ysbaddaden/clang.cr#3]
@ysbaddaden So cool that you made this!

Does it mean we can delete https://github.com/crystal-lang/crystal_lib ? It has many bugs and it's not feature complete. Plus it only has the necessary features to generate (incomplete) bindings, but it's not general clang bindings.

I would personally like to delete that project because we don't have much time to maintain it.

**Comment by ysbaddaden** [comment]
Well, the feature set is quite different. For example:

- I put everything under `LibC` because I didn't want to deal with aliases or references from LibX to LibC;
- I generate bindings for *everything* in the header and don't filter anything (may bloat memory);
- clang follow declarations to other headers... but doesn't generate anything for these because they don't belong to the file. For example it will know about `typedef usigned long uintptr_t` but I won't generate an `type UintptrT = ULong` alias (thought if it's a `#define` it may use the canonical type).

Last but not least there are **zero specs**.

I guess you can declare `crystal_lib` as discontinued, and we can improve things here.

In fact, I'd love for this to eventually make it into Crystal, so bindings are always generated from local headers :-)

**Comment by asterite** [comment]
Thank you for the reply!

So for now we can have both :-)
